In [28]:
import numpy as np
from sklearn import preprocessing

In [3]:
data1 = np.loadtxt("train.csv", delimiter=",")
data2 = np.loadtxt("test.csv", delimiter=",")
print("d1",data1.shape)
print("d2",data2.shape)

d1 (379, 14)
d2 (127, 13)


In [29]:
data1_scaled = preprocessing.scale(data1)
data1_scaled

array([[-4.00980675e-01, -4.90426876e-01, -1.28149216e+00, ...,
         4.20279958e-01, -1.10095452e+00,  1.63059527e+00],
       [-4.00533965e-01, -4.90426876e-01,  2.07534710e-01, ...,
         3.02579582e-01, -5.31432777e-01, -1.28982221e-01],
       [ 9.90079895e-02, -4.90426876e-01,  9.64253278e-01, ...,
        -3.72614514e+00,  8.60577894e-01, -1.05675944e+00],
       ...,
       [-4.01413194e-01, -4.90426876e-01,  2.07534710e-01, ...,
         3.42893853e-01, -3.47582313e-01, -1.92966858e-01],
       [-4.03579033e-01, -4.90426876e-01, -1.16949207e+00, ...,
         2.15898507e-01, -7.52606276e-01, -1.01294938e-03],
       [ 3.03242294e-01, -4.90426876e-01,  9.64253278e-01, ...,
         3.97907152e-01, -1.35806871e+00,  2.92095210e+00]])

In [61]:
data1_scaled.std(axis=0)


array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [62]:
data2_scaled = preprocessing.scale(data2)
data2_scaled

array([[ 3.88203164, -0.47968561,  1.19321481, ...,  0.86318341,
        -1.72394297,  1.14793924],
       [-0.4496825 , -0.47968561,  0.54572124, ..., -1.07706957,
         0.41293844, -0.87954882],
       [-0.4624454 , -0.47968561,  0.23746473, ...,  1.23275541,
         0.41293844, -0.46700418],
       ...,
       [-0.45831967,  2.09168571, -1.34873963, ..., -0.01455008,
         0.36041572, -0.656393  ],
       [-0.4494016 , -0.47968561, -0.28455761, ...,  1.18655891,
         0.30708851,  0.26852914],
       [-0.09779398, -0.47968561,  1.42247091, ..., -1.67762407,
        -3.12998863,  0.56949587]])

In [63]:
data2_scaled.std(axis=0)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [64]:
scaler = preprocessing.StandardScaler()
scaler.fit(data1)

scaler.transform(data1)

array([[-4.00980675e-01, -4.90426876e-01, -1.28149216e+00, ...,
         4.20279958e-01, -1.10095452e+00,  1.63059527e+00],
       [-4.00533965e-01, -4.90426876e-01,  2.07534710e-01, ...,
         3.02579582e-01, -5.31432777e-01, -1.28982221e-01],
       [ 9.90079895e-02, -4.90426876e-01,  9.64253278e-01, ...,
        -3.72614514e+00,  8.60577894e-01, -1.05675944e+00],
       ...,
       [-4.01413194e-01, -4.90426876e-01,  2.07534710e-01, ...,
         3.42893853e-01, -3.47582313e-01, -1.92966858e-01],
       [-4.03579033e-01, -4.90426876e-01, -1.16949207e+00, ...,
         2.15898507e-01, -7.52606276e-01, -1.01294938e-03],
       [ 3.03242294e-01, -4.90426876e-01,  9.64253278e-01, ...,
         3.97907152e-01, -1.35806871e+00,  2.92095210e+00]])

In [65]:
scaler.fit(data2)
scaler.transform(data2)

array([[ 3.88203164, -0.47968561,  1.19321481, ...,  0.86318341,
        -1.72394297,  1.14793924],
       [-0.4496825 , -0.47968561,  0.54572124, ..., -1.07706957,
         0.41293844, -0.87954882],
       [-0.4624454 , -0.47968561,  0.23746473, ...,  1.23275541,
         0.41293844, -0.46700418],
       ...,
       [-0.45831967,  2.09168571, -1.34873963, ..., -0.01455008,
         0.36041572, -0.656393  ],
       [-0.4494016 , -0.47968561, -0.28455761, ...,  1.18655891,
         0.30708851,  0.26852914],
       [-0.09779398, -0.47968561,  1.42247091, ..., -1.67762407,
        -3.12998863,  0.56949587]])

In [66]:
def step_gradient(points, learning_rate, m , c):
    m_slope = 0
    c_slope = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        m_slope += (-2/M)* (y - m * x - c)*x
        c_slope += (-2/M)* (y - m * x - c)
    new_m = m - learning_rate*m_slope
    new_c = c - learning_rate*c_slope
    return new_m, new_c

In [67]:
def gd(points, learning_rate, num_iterations):
    m = 0
    c = 0
    for i in range(num_iterations):
        m, c = step_gradient(points, learning_rate, m , c)
        print(i, " Cost: ", cost(points, m, c))
    return m, c

In [68]:
def cost(points, m, c):
    total_cost = 0
    M = len(points)
    for i in range(M):
        x = points[i, 0]
        y = points[i, 1]
        total_cost += (1/M)*((y - m*x - c)**2)
    return total_cost

In [99]:
def run():
    data1 = np.loadtxt("train.csv", delimiter=",")
    data2 = np.loadtxt("test.csv", delimiter=",")
    learning_rate = 0.9
    num_iterations = 1000
    m, c = gd(data1, learning_rate, num_iterations)
    print("coeffecient is ", m)
    print("cost is ,",c)
    np.savetxt("predict.csv",data2,fmt="%0.5f")
    

In [100]:
run()


0  Cost:  1.0026026153433896
1  Cost:  1.006770789995213
2  Cost:  1.0114889938513094
3  Cost:  1.016774604759101
4  Cost:  1.0226617821709536
5  Cost:  1.0291977370384668
6  Cost:  1.0364406318581794
7  Cost:  1.0444585382905522
8  Cost:  1.053329093303827
9  Cost:  1.0631396300647067
10  Cost:  1.0739876456339108
11  Cost:  1.085981522149491
12  Cost:  1.0992414531166317
13  Cost:  1.113900548956493
14  Cost:  1.1301061107091144
15  Cost:  1.148021070655569
16  Cost:  1.1678256054735214
17  Cost:  1.189718932543719
18  Cost:  1.2139213039330428
19  Cost:  1.2406762158741704
20  Cost:  1.270252854555265
21  Cost:  1.302948801932362
22  Cost:  1.3390930282229883
23  Cost:  1.3790492008324906
24  Cost:  1.4232193427800182
25  Cost:  1.4720478772909706
26  Cost:  1.5260260991607386
27  Cost:  1.5856971178219104
28  Cost:  1.6516613218142213
29  Cost:  1.7245824196160402
30  Cost:  1.8051941176036075
31  Cost:  1.8943075023202538
32  Cost:  1.9928192013276336
33  Cost:  2.1017204047468865

348  Cost:  59443501553961.26
349  Cost:  65712691137518.73
350  Cost:  72643058764211.88
351  Cost:  80304335361603.12
352  Cost:  88773606006880.19
353  Cost:  98136085529860.12
354  Cost:  108485975914705.92
355  Cost:  119927414127243.25
356  Cost:  132575519904575.03
357  Cost:  146557554049484.62
358  Cost:  162014198883985.3
359  Cost:  179100973745487.56
360  Cost:  197989799767806.9
361  Cost:  218870729691293.8
362  Cost:  241953860106831.9
363  Cost:  267471445374016.62
364  Cost:  295680234483043.75
365  Cost:  326864054372964.5
366  Cost:  361336665698763.8
367  Cost:  399444919780999.25
368  Cost:  441572248502082.9
369  Cost:  488142522263368.06
370  Cost:  539624314820405.7
371  Cost:  596535617907683.1
372  Cost:  659449053089711.1
373  Cost:  728997633278313.5
374  Cost:  805881131886444.5
375  Cost:  890873123702770.9
376  Cost:  984828768329771.8
377  Cost:  1088693414499648.5
378  Cost:  1203512111841577.0
379  Cost:  1330440125804439.0
380  Cost:  1470754561532433

668  Cost:  5.110490500532881e+27
669  Cost:  5.649466721234248e+27
670  Cost:  6.245285893987149e+27
671  Cost:  6.903942942266534e+27
672  Cost:  7.632065042204457e+27
673  Cost:  8.436978302911163e+27
674  Cost:  9.326781479214602e+27
675  Cost:  1.0310427458490082e+28
676  Cost:  1.1397813341471994e+28
677  Cost:  1.2599880023409048e+28
678  Cost:  1.392872227751357e+28
679  Cost:  1.5397710448326279e+28
680  Cost:  1.7021624979432e+28
681  Cost:  1.8816805129097455e+28
682  Cost:  2.0801313370155257e+28
683  Cost:  2.2995117128268556e+28
684  Cost:  2.542028968716236e+28
685  Cost:  2.810123228226017e+28
686  Cost:  3.10649196173535e+28
687  Cost:  3.4341171274607894e+28
688  Cost:  3.796295174873621e+28
689  Cost:  4.196670212417844e+28
690  Cost:  4.6392706732509395e+28
691  Cost:  5.128549847924831e+28
692  Cost:  5.6694306918330355e+28
693  Cost:  6.267355358260622e+28
694  Cost:  6.928339955421243e+28
695  Cost:  7.659035078427122e+28
696  Cost:  8.466792725243914e+28
697  Co